name: Publish
on:
  #  pull_request:
  #    branches:
  #      - master
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Test app
        run: bun test

  publish:
    needs:
      - test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build distribution files
        run: bun dist.ts
      - name: publish
        run: npm publish
